name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
      
    
    - name: Generate coverage report
      run: |
        go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage report
      uses: codecov/codecov-action@v1.0.2
      with:
        token: c561f428-9108-4833-8d0c-f681c6ea7971
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella

    - uses: actions/upload-artifact@v2
      with:
        name: ctcli-binary
        path: ./ctcli
